stages:
  - build
  - test
  - deploy

build:
  stage: build
  image: razonyang/hugo
  script:
    - hugo  
  artifacts:
    paths:
      - public/  

test:
  stage: test
  image: alpine:latest  
  script:
    - echo "Ejecutando pruebas..."  

deploy:
  stage: deploy
  image: alpine:latest  
  script:
    - echo "Desplegando el sitio web..."  